/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Meseros;

import Cocina.Cocina;
import static Meseros.Menu.mesa;
import javax.swing.table.DefaultTableModel;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;


/**
 *
 * @author tepes
 */
public class Pedidos extends javax.swing.JFrame {

    /**
     * Creates new form Platos
     */

     static Object [] vector = new Object [3];
    
     
    public Pedidos() {
            initComponents();
            
            DefaultTableModel model = (DefaultTableModel) Table.getModel();
           
            nodo();
            }
     
   public void nodo (){
      
   DefaultTableModel model = (DefaultTableModel) Table.getModel();
   int plato1 = Integer.parseInt( Menu.spinner1.getValue().toString());
   int plato2 = Integer.parseInt( Menu.spinner2.getValue().toString());
   int plato3 = Integer.parseInt( Menu.spinner3.getValue().toString());
   int plato4 = Integer.parseInt( Menu.spinner4.getValue().toString());
   int plato5 = Integer.parseInt( Menu.spinner5.getValue().toString());
   int plato6 = Integer.parseInt( Menu.spinner6.getValue().toString());
   int plato7 = Integer.parseInt( Menu.spinner7.getValue().toString());
   int plato8 = Integer.parseInt( Menu.spinner8.getValue().toString());
   int plato9 = Integer.parseInt( Menu.spinner9.getValue().toString());
   if (plato1 > 0 ) {
           vector[0] = plato1;
           vector[1] = "Insalata caprese";
           vector[2] = mesa;
           model.addRow(vector);
           Table.setModel(model);
       }    
   if (plato2 > 0) {
           vector[0] = plato2;
           vector[1] = "Insalata Macedonia";
           vector[2] = mesa;
           model.addRow(vector);
           Table.setModel(model);
       }
   if (plato3 > 0) {
           vector[0] = plato3;
           vector[1] = "Insalata Di pollo";
           vector[2] = mesa;
           model.addRow(vector);
           Table.setModel(model);
       }
   if (plato4 > 0) {
           vector[0] = plato4;
           vector[1] = "Lasagne di carne";
           vector[2] = mesa;
           model.addRow(vector);
           Table.setModel(model);
       }
   if (plato5 > 0) {
           vector[0] = plato5;
           vector[1] = "Lasagne Petto di pollo";
           vector[2] = mesa;
           model.addRow(vector);
           Table.setModel(model);
       }
   if (plato6 > 0) {
           vector[0] = plato6;
           vector[1] = "Lasagne Vegetariane";
           vector[2] = mesa;
           model.addRow(vector);
           Table.setModel(model);
       }
   if (plato7 > 0) {
           vector[0] = plato7;
           vector[1] = "spaghetti bolognese";
           vector[2] = mesa;
           model.addRow(vector);
           Table.setModel(model);
       }
   if (plato8 > 0) {
           vector[0] = plato8;
           vector[1] = "spaghetti Pesto";
           vector[2] = mesa;
           model.addRow(vector);
           Table.setModel(model);
       }
   if (plato9 > 0) {
           vector[0] = plato9;
           vector[1] = "spaghetti Carbonara";
           vector[2] = mesa;
           model.addRow(vector);
           Table.setModel(model);
       }
    
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButtom = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BackButtom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back-button.png"))); // NOI18N
        BackButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtomActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("           Pedidos");

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Plato", "Cantidad", "Mesa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BackButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BackButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtomActionPerformed
        // TODO add your handling code here:
        Menu a = new Menu();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButtom;
    private javax.swing.JTable Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
