/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Meseros;

import Principal.Inicio;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Panel;
import static java.lang.Integer.parseInt;
import javax.swing.DefaultListModel;
import javax.swing.JScrollPane;
import javax.swing.JOptionPane; 
import java.io.*;
import javax.swing.JLabel;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author Elisvan Ruidiaz
 */
public class PlatosFuertes extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
        public PlatosFuertes() {
        initComponents();
        Panel panel = new Panel ();
     
        spinner1.setVisible(false);
        spinner2.setVisible(false);
        spinner3.setVisible(false);
        spinner4.setVisible(false);
        spinner5.setVisible(false);
        spinner6.setVisible(false);
        spinner7.setVisible(false);
        spinner8.setVisible(false);
        spinner9.setVisible(false);
        confspinner();
        label1.setVisible(false);
        label2.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        label6.setVisible(false);
        label7.setVisible(false);
        label8.setVisible(false);
        label9.setVisible(false);
        this.getContentPane().setBackground(Color.white);       
    }
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();
        Plato1 = new javax.swing.JButton();
        Plato2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Plato3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        Plato4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Plato5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Plato6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        Plato7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        plato8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Plato9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spinner1 = new javax.swing.JSpinner();
        spinner2 = new javax.swing.JSpinner();
        spinner3 = new javax.swing.JSpinner();
        spinner4 = new javax.swing.JSpinner();
        spinner5 = new javax.swing.JSpinner();
        spinner6 = new javax.swing.JSpinner();
        spinner7 = new javax.swing.JSpinner();
        spinner8 = new javax.swing.JSpinner();
        spinner9 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        PedirButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setText("Antipasti");

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setAutoscrolls(true);

        Plato1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ensaladacaprese-iloveimg-resized.jpg"))); // NOI18N
        Plato1.setText("Insalata caprese");
        Plato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plato1ActionPerformed(evt);
            }
        });

        Plato2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img_ensalada_de_frutas_para_diabeticos_57467_300_150-iloveimg-resized.jpg"))); // NOI18N
        Plato2.setText("jButton1");
        Plato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plato2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Insalata caprese");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("Insalata Macedonia");

        Plato3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ensaladapollo.jpg"))); // NOI18N
        Plato3.setText("jButton3");
        Plato3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plato3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("insalata di pollo");

        Plato4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lasañacarne.jpg"))); // NOI18N
        Plato4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plato4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setText("Lasagne di carne");

        Plato5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ensaladapollo.jpg"))); // NOI18N
        Plato5.setText("jButton6");
        Plato5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plato5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel10.setText("Lasagne Petto di pollo");

        Plato6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vegetarian-lasagna-300x176-iloveimg-resized.jpg"))); // NOI18N
        Plato6.setText("jButton7");
        Plato6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plato6ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel11.setText("lasagne vegetariane");

        Plato7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img-receta-spaghetti-salsa-bolognese-iloveimg-resized.jpg"))); // NOI18N
        Plato7.setText("jButton8");
        Plato7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plato7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("spaghetti  Pesto");

        plato8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spaghettis-pesto-iloveimg-resized.jpg"))); // NOI18N
        plato8.setText("jButton8");
        plato8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plato8ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 0));
        jLabel3.setText("spaghetti  bolognese");

        Plato9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EspaguetisALaCarbonaraConNata-iloveimg-resized.jpg"))); // NOI18N
        Plato9.setText("jButton8");
        Plato9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Plato9ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 0));
        jLabel4.setText("spaghetti  Carbonara");

        spinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner1StateChanged(evt);
            }
        });

        spinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner2StateChanged(evt);
            }
        });

        spinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner3StateChanged(evt);
            }
        });

        spinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner4StateChanged(evt);
            }
        });

        spinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner5StateChanged(evt);
            }
        });

        spinner6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner6StateChanged(evt);
            }
        });

        spinner7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner7StateChanged(evt);
            }
        });

        spinner8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner8StateChanged(evt);
            }
        });

        spinner9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner9StateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel6.setText("$ !0.000");

        label1.setText("jLabel12");

        label2.setText("jLabel12");

        label3.setText("jLabel12");

        label4.setText("jLabel12");

        label5.setText("jLabel12");

        label6.setText("jLabel12");

        label7.setText("jLabel12");

        label8.setText("jLabel12");

        label9.setText("jLabel12");

        label10.setText("$ 9.000");

        jLabel12.setText("$ 20.000");

        jLabel13.setText("$ 25.000");

        jLabel14.setText("$ 30.000");

        jLabel15.setText("$ 20.000");

        jLabel16.setText("$ 16.000");

        jLabel17.setText("$ 19.000");

        jLabel18.setText("$ 19.000");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(Plato2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                                .addComponent(spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69))
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(label2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(label10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Plato5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(22, 22, 22)))
                        .addGap(40, 40, 40)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Plato3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel11))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(spinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(label3)))
                                .addGap(53, 53, 53)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel14))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(Plato6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(spinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(label6))))))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(Plato1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label1))
                            .addComponent(jLabel6))
                        .addGap(85, 85, 85)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(Plato4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(Plato7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(plato8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label7)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(Plato9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(spinner9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(label9)))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Plato7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(6, 6, 6)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(label1))
                                    .addComponent(Plato1)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Plato4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(spinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(label7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))))
                .addGap(7, 7, 7)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(Plato2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(label2))
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(label10))
                                    .addComponent(Plato5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(spinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(label8))
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(plato8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(14, 14, 14)
                        .addComponent(spinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Plato3))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(spinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(label3))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(spinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(label6))
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Plato6)
                                        .addComponent(Plato9)
                                        .addComponent(label9))))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinner9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(Panel);

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back-button.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });

        PedirButtom.setText("Pedir");
        PedirButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PedirButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PedirButtom)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Back, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PedirButtom)
                .addGap(4, 4, 4))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    static void confspinner(){
    
        SpinnerNumberModel model1 = new SpinnerNumberModel(); 
        model1.setMaximum(30);
        model1.setMinimum(0);
        SpinnerNumberModel model2 = new SpinnerNumberModel(); 
        model2.setMaximum(30);
        model2.setMinimum(0);
        SpinnerNumberModel model3 = new SpinnerNumberModel(); 
        model3.setMaximum(30);
        model3.setMinimum(0);
        SpinnerNumberModel model4 = new SpinnerNumberModel(); 
        model4.setMaximum(30);
        model4.setMinimum(0);
        SpinnerNumberModel model5 = new SpinnerNumberModel(); 
        model5.setMaximum(30);
        model5.setMinimum(0);
        SpinnerNumberModel model6 = new SpinnerNumberModel(); 
        model6.setMaximum(30);
        model6.setMinimum(0);
        SpinnerNumberModel model7 = new SpinnerNumberModel(); 
        model7.setMaximum(30);
        model7.setMinimum(0);
        SpinnerNumberModel model8 = new SpinnerNumberModel(); 
        model8.setMaximum(30);
        model8.setMinimum(0);
        SpinnerNumberModel model9 = new SpinnerNumberModel(); 
        model9.setMaximum(30);
        model9.setMinimum(0);
        spinner1.setModel(model1);
        spinner2.setModel(model2);
        spinner3.setModel(model3);
        spinner4.setModel(model4);
        spinner5.setModel(model5);
        spinner6.setModel(model6);
        spinner7.setModel(model7);
        spinner8.setModel(model8);
        spinner9.setModel(model9);
        
            
    }
    
        public static String nomb;        
    public void Escribira(String nombre){
        File f;
        FileWriter w;
        BufferedWriter wb;
        PrintWriter wr;
        try{
            f = new File(nombre);
            w = new FileWriter(f);
            wb = new BufferedWriter(w);
            wr = new PrintWriter(wb);
            
            wr.write("Intento de factura 1");
            wr.close();
            wb.close();
        }catch(Exception e){}
    }    
    
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
        Inicio a = new Inicio();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void Plato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plato3ActionPerformed
        // TODO add your handling code here:
        spinner3.setVisible(true);
        nomb = "insalata di pollo";
    }//GEN-LAST:event_Plato3ActionPerformed

    private void Plato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plato2ActionPerformed
        // TODO add your handling code here:
        spinner2.setVisible(true);
        nomb = "Insalata Macedonia";
    }//GEN-LAST:event_Plato2ActionPerformed

    private void Plato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plato1ActionPerformed
        spinner1.setVisible(true);
        nomb = "Insalata Caprese";
    }//GEN-LAST:event_Plato1ActionPerformed

    private void Plato6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plato6ActionPerformed
        // TODO add your handling code here:
        spinner6.setVisible(true);
    }//GEN-LAST:event_Plato6ActionPerformed

    private void Plato4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plato4ActionPerformed
        // TODO add your handling code here:
        spinner4.setVisible(true);
    }//GEN-LAST:event_Plato4ActionPerformed

    private void Plato5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plato5ActionPerformed
        // TODO add your handling code here:
        spinner5.setVisible(true);
    }//GEN-LAST:event_Plato5ActionPerformed

    private void Plato7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plato7ActionPerformed
        // TODO add your handling code here:
        spinner7.setVisible(true);
    }//GEN-LAST:event_Plato7ActionPerformed

    private void plato8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plato8ActionPerformed
        // TODO add your handling code here:
        spinner8.setVisible(true);
    }//GEN-LAST:event_plato8ActionPerformed

    private void Plato9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Plato9ActionPerformed
        // TODO add your handling code here:
        spinner9.setVisible(true);
    }//GEN-LAST:event_Plato9ActionPerformed
    static int mesa;
    private void PedirButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PedirButtomActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(PlatosFuertes.this, "Confirmar Pedido","Confirmar Pedido",0);
        if (dialogResult == JOptionPane.YES_OPTION) {
            int Mesa = Integer.parseInt(JOptionPane.showInputDialog(PlatosFuertes.this, "Digite Numero de Mesa","Pedidos",1));
            int Mesas = Integer.valueOf(Mesa);
                if (Mesa <1 || Mesa >20) {                    
                    JOptionPane.showMessageDialog(PlatosFuertes.this, "Ingrese un numero de Mesa Valido","",2);
                }
                else {
                mesa = Mesa;
                Pedidos a = new Pedidos();
                a.setVisible(true);
                this.dispose();
                
                }
               
        }
        
    }//GEN-LAST:event_PedirButtomActionPerformed

    private void spinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner1StateChanged
        if (spinner1.getValue().toString().equals(0)) {
            label1.setVisible(false);
        }else{
            label1.setVisible(true);
            
            int a = parseInt("10000");
            int b = parseInt(spinner1.getValue().toString());
            label1.setText("El precio es: " +(a * b));
            
        }
    }//GEN-LAST:event_spinner1StateChanged

    private void spinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner2StateChanged
        // TODO add your handling code here:
        if (spinner2.getValue().toString().equals(0)) {
            label2.setVisible(false);
        }else{
            label2.setVisible(true);
            
            int a = parseInt("9000");
            int b = parseInt(spinner2.getValue().toString());
            label2.setText("El precio es: " +(a * b));             
        }
    }//GEN-LAST:event_spinner2StateChanged

    private void spinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner3StateChanged
        // TODO add your handling code here:
        if (spinner3.getValue().toString().equals(0)) {
            label3.setVisible(false);
        }else{
            label3.setVisible(true);
            
            int a = parseInt("20000");
            int b = parseInt(spinner3.getValue().toString());
            label3.setText("El precio es: " +(a * b));             
        }
    }//GEN-LAST:event_spinner3StateChanged

    private void spinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner4StateChanged
        // TODO add your handling code here:
          if (spinner4.getValue().toString().equals(0)) {
            label4.setVisible(false);
        }else{
            label4.setVisible(true);
            
            int a = parseInt("20000");
            int b = parseInt(spinner4.getValue().toString());
            label4.setText("El precio es: " +(a * b));             
        }
    }//GEN-LAST:event_spinner4StateChanged

    private void spinner5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner5StateChanged
        // TODO add your handling code here:
        if (spinner5.getValue().toString().equals(0)) {
            label5.setVisible(false);
        }else{
            label5.setVisible(true);
            
            int a = parseInt("25000");
            int b = parseInt(spinner5.getValue().toString());
            label5.setText("El precio es: " +(a * b));             
        }
        
    }//GEN-LAST:event_spinner5StateChanged

    private void spinner6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner6StateChanged
        // TODO add your handling code here:
         if (spinner6.getValue().toString().equals(0)) {
            label6.setVisible(false);
        }else{
            label6.setVisible(true);
            
            int a = parseInt("30000");
            int b = parseInt(spinner6.getValue().toString());
            label6.setText("El precio es: " +(a * b));
         }
    }//GEN-LAST:event_spinner6StateChanged

    private void spinner7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner7StateChanged
        // TODO add your handling code here:
         if (spinner7.getValue().toString().equals(0)) {
            label7.setVisible(false);
        }else{
            label7.setVisible(true);
            
            int a = parseInt("16000");
            int b = parseInt(spinner7.getValue().toString());
            label7.setText("El precio es: " +(a * b));
         }        
    }//GEN-LAST:event_spinner7StateChanged

    private void spinner8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner8StateChanged
        // TODO add your handling code here:
         if (spinner8.getValue().toString().equals(0)) {
            label8.setVisible(false);
        }else{
            label8.setVisible(true);
            
            int a = parseInt("19000");
            int b = parseInt(spinner8.getValue().toString());
            label8.setText("El precio es: " +(a * b));
         }
    }//GEN-LAST:event_spinner8StateChanged

    private void spinner9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner9StateChanged
        // TODO add your handling code here:
         if (spinner9.getValue().toString().equals(0)) {
            label9.setVisible(false);
        }else{
            label9.setVisible(true);
            
            int a = parseInt("19000");
            int b = parseInt(spinner9.getValue().toString());
            label9.setText("El precio es: " +(a * b));
         }
    }//GEN-LAST:event_spinner9StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlatosFuertes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlatosFuertes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlatosFuertes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlatosFuertes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlatosFuertes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPanel Panel;
    private javax.swing.JButton PedirButtom;
    private javax.swing.JButton Plato1;
    private javax.swing.JButton Plato2;
    private javax.swing.JButton Plato3;
    private javax.swing.JButton Plato4;
    private javax.swing.JButton Plato5;
    private javax.swing.JButton Plato6;
    private javax.swing.JButton Plato7;
    private javax.swing.JButton Plato9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JButton plato8;
    public static javax.swing.JSpinner spinner1;
    public static javax.swing.JSpinner spinner2;
    public static javax.swing.JSpinner spinner3;
    public static javax.swing.JSpinner spinner4;
    public static javax.swing.JSpinner spinner5;
    public static javax.swing.JSpinner spinner6;
    public static javax.swing.JSpinner spinner7;
    public static javax.swing.JSpinner spinner8;
    public static javax.swing.JSpinner spinner9;
    // End of variables declaration//GEN-END:variables
}
