/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Meseros;

import Principal.Inicio;
import java.awt.Panel;
import static java.lang.Integer.parseInt;
import javax.swing.JOptionPane;
import java.io.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import static jdk.nashorn.internal.objects.NativeRegExp.test;

/**
 *
 * @author Elisvan Ruidiaz
 */
public class PlatosFuertes extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public static String nomb;
    static Object[] vector = new Object[4];
    private final String ruta = System.getProperties().getProperty("user.dir");

    public PlatosFuertes() {
        initComponents();
        Panel panel = new Panel();
        spinner1.setVisible(false);
        spinner2.setVisible(false);
        spinner3.setVisible(false);
        spinner4.setVisible(false);
        spinner5.setVisible(false);
        spinner6.setVisible(false);
        spinner7.setVisible(false);
        spinner8.setVisible(false);
        spinner9.setVisible(false);
        label1.setVisible(false);
        label2.setVisible(false);
        label3.setVisible(false);
        label4.setVisible(false);
        label5.setVisible(false);
        label6.setVisible(false);
        label7.setVisible(false);
        label8.setVisible(false);
        label9.setVisible(false);
        confspinner();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Panel = new javax.swing.JPanel();
        plato1 = new javax.swing.JButton();
        plato2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        plato3 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        plato4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        plato5 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        plato6 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        plato7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        plato8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        plato9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        spinner1 = new javax.swing.JSpinner();
        spinner2 = new javax.swing.JSpinner();
        spinner3 = new javax.swing.JSpinner();
        spinner4 = new javax.swing.JSpinner();
        spinner5 = new javax.swing.JSpinner();
        spinner6 = new javax.swing.JSpinner();
        spinner7 = new javax.swing.JSpinner();
        spinner8 = new javax.swing.JSpinner();
        spinner9 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label6 = new javax.swing.JLabel();
        label7 = new javax.swing.JLabel();
        label8 = new javax.swing.JLabel();
        label9 = new javax.swing.JLabel();
        label10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        pedirButtom = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPedidos = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setText("Antipasti");

        Panel.setBackground(new java.awt.Color(255, 255, 255));
        Panel.setAutoscrolls(true);

        plato1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ensaladacaprese-iloveimg-resized.jpg"))); // NOI18N
        plato1.setText("Insalata caprese");
        plato1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plato1ActionPerformed(evt);
            }
        });

        plato2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img_ensalada_de_frutas_para_diabeticos_57467_300_150-iloveimg-resized.jpg"))); // NOI18N
        plato2.setText("jButton1");
        plato2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plato2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 51));
        jLabel5.setText("Insalata caprese");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("Insalata Macedonia");

        plato3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ensaladapollo.jpg"))); // NOI18N
        plato3.setText("jButton3");
        plato3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plato3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 51));
        jLabel8.setText("insalata di pollo");

        plato4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lasañacarne.jpg"))); // NOI18N
        plato4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plato4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel9.setText("Lasagne di carne");

        plato5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ensaladapollo.jpg"))); // NOI18N
        plato5.setText("jButton6");
        plato5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plato5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel10.setText("Lasagne Petto di pollo");

        plato6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/vegetarian-lasagna-300x176-iloveimg-resized.jpg"))); // NOI18N
        plato6.setText("jButton7");
        plato6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plato6ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel11.setText("lasagne vegetariane");

        plato7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/img-receta-spaghetti-salsa-bolognese-iloveimg-resized.jpg"))); // NOI18N
        plato7.setText("jButton8");
        plato7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plato7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 0));
        jLabel1.setText("spaghetti  Pesto");

        plato8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/spaghettis-pesto-iloveimg-resized.jpg"))); // NOI18N
        plato8.setText("jButton8");
        plato8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plato8ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 0));
        jLabel3.setText("spaghetti  bolognese");

        plato9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/EspaguetisALaCarbonaraConNata-iloveimg-resized.jpg"))); // NOI18N
        plato9.setText("jButton8");
        plato9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plato9ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 0));
        jLabel4.setText("spaghetti  Carbonara");

        spinner1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner1StateChanged(evt);
            }
        });

        spinner2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner2StateChanged(evt);
            }
        });

        spinner3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner3StateChanged(evt);
            }
        });

        spinner4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner4StateChanged(evt);
            }
        });

        spinner5.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner5StateChanged(evt);
            }
        });

        spinner6.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner6StateChanged(evt);
            }
        });

        spinner7.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner7StateChanged(evt);
            }
        });

        spinner8.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner8StateChanged(evt);
            }
        });

        spinner9.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinner9StateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 11)); // NOI18N
        jLabel6.setText("$ !0.000");

        label1.setText("jLabel12");

        label2.setText("jLabel12");

        label3.setText("jLabel12");

        label4.setText("jLabel12");

        label5.setText("jLabel12");

        label6.setText("jLabel12");

        label7.setText("jLabel12");

        label8.setText("jLabel12");

        label9.setText("jLabel12");

        label10.setText("$ 9.000");

        jLabel12.setText("$ 20.000");

        jLabel13.setText("$ 25.000");

        jLabel14.setText("$ 30.000");

        jLabel15.setText("$ 20.000");

        jLabel16.setText("$ 16.000");

        jLabel17.setText("$ 19.000");

        jLabel18.setText("$ 19.000");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(plato2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                                .addComponent(spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69))
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(label2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(label10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(plato5, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)
                                .addGap(22, 22, 22)))
                        .addGap(40, 40, 40)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label5)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plato3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel11))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(spinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(label3)))
                                .addGap(53, 53, 53)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel14))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(plato6, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addGap(29, 29, 29)
                                                .addComponent(spinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(label6))))))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(plato1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(label1))
                            .addComponent(jLabel6))
                        .addGap(85, 85, 85)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(plato4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(label4))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel17)
                                .addComponent(plato7, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(plato8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(label7)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(plato9, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(spinner9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(label9)))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(plato7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(6, 6, 6)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(spinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(label1))
                                    .addComponent(plato1)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(plato4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(spinner7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)
                                .addComponent(label7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))))
                .addGap(7, 7, 7)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(plato2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(label2))
                                            .addGroup(PanelLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(spinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(label10))
                                    .addComponent(plato5, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(spinner8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(label8))
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(plato8, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(label5)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17))))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(14, 14, 14)
                        .addComponent(spinner5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(plato3))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(spinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(label3))
                                    .addGroup(PanelLayout.createSequentialGroup()
                                        .addComponent(spinner6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(label6))
                                    .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(plato6)
                                        .addComponent(plato9)
                                        .addComponent(label9))))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinner9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel18))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(Panel);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/back-button.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        pedirButtom.setText("Pedir");
        pedirButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirButtomActionPerformed(evt);
            }
        });

        TablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Plato", "Mesa", "Mesero"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaPedidos);
        if (TablaPedidos.getColumnModel().getColumnCount() > 0) {
            TablaPedidos.getColumnModel().getColumn(0).setResizable(false);
            TablaPedidos.getColumnModel().getColumn(1).setResizable(false);
            TablaPedidos.getColumnModel().getColumn(2).setResizable(false);
            TablaPedidos.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel19.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel19.setText("Pedido");

        jButton1.setText("Cocina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(261, 261, 261)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33)
                .addComponent(pedirButtom)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pedirButtom)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    static void confspinner() {
        SpinnerNumberModel model1 = new SpinnerNumberModel();
        model1.setMaximum(30);
        model1.setMinimum(0);
        SpinnerNumberModel model2 = new SpinnerNumberModel();
        model2.setMaximum(30);
        model2.setMinimum(0);
        SpinnerNumberModel model3 = new SpinnerNumberModel();
        model3.setMaximum(30);
        model3.setMinimum(0);
        SpinnerNumberModel model4 = new SpinnerNumberModel();
        model4.setMaximum(30);
        model4.setMinimum(0);
        SpinnerNumberModel model5 = new SpinnerNumberModel();
        model5.setMaximum(30);
        model5.setMinimum(0);
        SpinnerNumberModel model6 = new SpinnerNumberModel();
        model6.setMaximum(30);
        model6.setMinimum(0);
        SpinnerNumberModel model7 = new SpinnerNumberModel();
        model7.setMaximum(30);
        model7.setMinimum(0);
        SpinnerNumberModel model8 = new SpinnerNumberModel();
        model8.setMaximum(30);
        model8.setMinimum(0);
        SpinnerNumberModel model9 = new SpinnerNumberModel();
        model9.setMaximum(30);
        model9.setMinimum(0);
        spinner1.setModel(model1);
        spinner2.setModel(model2);
        spinner3.setModel(model3);
        spinner4.setModel(model4);
        spinner5.setModel(model5);
        spinner6.setModel(model6);
        spinner7.setModel(model7);
        spinner8.setModel(model8);
        spinner9.setModel(model9);
    }

    public void escribira(String nombre) {
        File f;
        FileWriter w;
        BufferedWriter wb;
        PrintWriter wr;
        try {
            f = new File(nombre);
            w = new FileWriter(f);
            wb = new BufferedWriter(w);
            wr = new PrintWriter(wb);
            tablaArchi();
            wr.close();
            wb.close();
        } catch (IOException e) {
        }
    }

    public void nodo() {
        DefaultTableModel model = (DefaultTableModel) TablaPedidos.getModel();
        int plato1 = Integer.parseInt(PlatosFuertes.spinner1.getValue().toString());
        int plato2 = Integer.parseInt(PlatosFuertes.spinner2.getValue().toString());
        int plato3 = Integer.parseInt(PlatosFuertes.spinner3.getValue().toString());
        int plato4 = Integer.parseInt(PlatosFuertes.spinner4.getValue().toString());
        int plato5 = Integer.parseInt(PlatosFuertes.spinner5.getValue().toString());
        int plato6 = Integer.parseInt(PlatosFuertes.spinner6.getValue().toString());
        int plato7 = Integer.parseInt(PlatosFuertes.spinner7.getValue().toString());
        int plato = Integer.parseInt(PlatosFuertes.spinner8.getValue().toString());
        int plato9 = Integer.parseInt(PlatosFuertes.spinner9.getValue().toString());
        if (plato1 > 0) {
            vector[0] = plato1;
            vector[1] = "Insalata caprese";
            vector[2] = mesa;
            vector[3] = mesero;
            model.addRow(vector);
        }
        if (plato2 > 0) {
            vector[0] = plato2;
            vector[1] = "Insalata Macedonia";
            vector[2] = mesa;
            vector[3] = mesero;
            model.addRow(vector);
        }
        if (plato3 > 0) {
            vector[0] = plato3;
            vector[1] = "Insalata Di pollo";
            vector[2] = mesa;
            vector[3] = mesero;
            model.addRow(vector);
        }
        if (plato4 > 0) {
            vector[0] = plato4;
            vector[1] = "Lasagne di carne";
            vector[2] = mesa;
            vector[3] = mesero;
            model.addRow(vector);
        }
        if (plato5 > 0) {
            vector[0] = plato5;
            vector[1] = "Lasagne Petto di pollo";
            vector[2] = mesa;
            vector[3] = mesero;
            model.addRow(vector);
        }
        if (plato6 > 0) {
            vector[0] = plato6;
            vector[1] = "Lasagne Vegetariane";
            vector[2] = mesa;
            vector[3] = mesero;
            model.addRow(vector);
        }
        if (plato7 > 0) {
            vector[0] = plato7;
            vector[1] = "spaghetti bolognese";
            vector[2] = mesa;
            vector[3] = mesero;
            model.addRow(vector);
        }
        if (plato > 0) {
            vector[0] = plato;
            vector[1] = "spaghetti Pesto";
            vector[2] = mesa;
            vector[3] = mesero;
            model.addRow(vector);
        }
        if (plato9 > 0) {
            vector[0] = plato9;
            vector[1] = "spaghetti Carbonara";
            vector[2] = mesa;
            vector[3] = mesero;
            model.addRow(vector);
        }
    }

    void guardarArchivo() {
        File archivo = null;
        FileReader fr = null;
        BufferedReader br;
        try {
            // Apertura del fichero y creacion de BufferedReader para poder
            // hacer una lectura comoda (disponer del metodo readLine()).
            archivo = new File(ruta + "//ArchiPedidos.txt");
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);
            // Lectura del fichero
            String linea;
            DefaultTableModel model_tabla = new DefaultTableModel();
            model_tabla.addColumn("Cantidad");
            model_tabla.addColumn("Plato");
            model_tabla.addColumn("Mesa");
            model_tabla.addColumn("Mesero");
            while ((linea = br.readLine()) != null) {
                System.out.println(linea);
                model_tabla.addRow(new String[]{linea});
            }
            TablaPedidos.setModel(model_tabla);
            br.close();

        } catch (IOException e) {
        } finally {
            try {
                if (null != fr) {
                    fr.close();
                }
            } catch (IOException e) {
            }
        }
        FileWriter w;
        BufferedWriter wb;
        PrintWriter wr;
        try {
            w = new FileWriter(archivo, false);
            wb = new BufferedWriter(w);
            wr = new PrintWriter(wb);
            wr.write(mesa);
            wr.write(mesero);

            wr.close();
            wb.close();
        } catch (IOException e) {
        }
    }

    private void tablaArchi() {
        nodo();
        try {
            String x = (ruta + "//ArchiPedidos.txt");
            try (BufferedWriter bfw = new BufferedWriter(new FileWriter(x))) {
                System.out.println("Que esta pasando willy");
                System.out.println(TablaPedidos.getRowCount());
                System.out.println(TablaPedidos.getColumnCount());                
                for (int i = 0; i < TablaPedidos.getRowCount(); i++) //realiza un barrido por filas.
                {
                    System.out.println(i);
                    for (int j = 0; j < TablaPedidos.getColumnCount(); j++) //realiza un barrido por columnas.
                    {
                        System.out.println(j);
                        bfw.write((TablaPedidos.getValueAt(i, j).toString()));
                        if (j < TablaPedidos.getColumnCount() - 1) { //agrega separador "," si no es el ultimo elemento de la fila.
                            System.out.println(j);
                            bfw.write(",");
                        }
                    }
                    bfw.newLine(); //inserta nueva linea.
                }
                //cierra archivo!
            }
            System.out.println("El archivo fue salvado correctamente!");
        } catch (IOException e) {
            System.out.println("ERROR: Ocurrio un problema al salvar el archivo!" + e.getMessage());
        }
    }

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        Inicio a = new Inicio();
        a.setVisible(true);
        this.hide();
    }//GEN-LAST:event_backActionPerformed

    private void plato3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plato3ActionPerformed
        // TODO add your handling code here:
        spinner3.setVisible(true);
    }//GEN-LAST:event_plato3ActionPerformed

    private void plato2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plato2ActionPerformed
        // TODO add your handling code here:
        spinner2.setVisible(true);
    }//GEN-LAST:event_plato2ActionPerformed

    private void plato1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plato1ActionPerformed
        spinner1.setVisible(true);
    }//GEN-LAST:event_plato1ActionPerformed

    private void plato6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plato6ActionPerformed
        // TODO add your handling code here:
        spinner6.setVisible(true);
    }//GEN-LAST:event_plato6ActionPerformed

    private void plato4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plato4ActionPerformed
        // TODO add your handling code here:
        spinner4.setVisible(true);
    }//GEN-LAST:event_plato4ActionPerformed

    private void plato5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plato5ActionPerformed
        // TODO add your handling code here:
        spinner5.setVisible(true);
    }//GEN-LAST:event_plato5ActionPerformed

    private void plato7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plato7ActionPerformed
        // TODO add your handling code here:
        spinner7.setVisible(true);
    }//GEN-LAST:event_plato7ActionPerformed

    private void plato8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plato8ActionPerformed
        // TODO add your handling code here:
        spinner8.setVisible(true);
    }//GEN-LAST:event_plato8ActionPerformed

    private void plato9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plato9ActionPerformed
        // TODO add your handling code here:
        spinner9.setVisible(true);
    }//GEN-LAST:event_plato9ActionPerformed
    static int mesa;
    static int mesero;
    private void pedirButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirButtomActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(PlatosFuertes.this, "Confirmar Pedido", "Confirmar Pedido", 0);
        if (dialogResult == JOptionPane.YES_OPTION) {
            int Mesa = Integer.parseInt(JOptionPane.showInputDialog(PlatosFuertes.this, "Digite Numero de Mesa", "Pedidos", 1));
            int Mesero = Integer.parseInt(JOptionPane.showInputDialog(PlatosFuertes.this, "Digite Numero de Mesero", "Meseros", 1));
            mesa = Mesa;
            mesero = Mesero;
            nodo();
            tablaArchi();
        }
    }//GEN-LAST:event_pedirButtomActionPerformed

    private void spinner1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner1StateChanged
        if (spinner1.getValue().toString().equals(0)) {
            label1.setVisible(false);
        } else {
            label1.setVisible(true);
            int a = parseInt("10000");
            int b = parseInt(spinner1.getValue().toString());
            label1.setText("El precio es: " + (a * b));
        }
    }//GEN-LAST:event_spinner1StateChanged

    private void spinner2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner2StateChanged
        // TODO add your handling code here:
        if (spinner2.getValue().toString().equals(0)) {
            label2.setVisible(false);
        } else {
            label2.setVisible(true);
            int a = parseInt("9000");
            int b = parseInt(spinner2.getValue().toString());
            label2.setText("El precio es: " + (a * b));
        }
    }//GEN-LAST:event_spinner2StateChanged

    private void spinner3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner3StateChanged
        // TODO add your handling code here:
        if (spinner3.getValue().toString().equals(0)) {
            label3.setVisible(false);
        } else {
            label3.setVisible(true);
            int a = parseInt("20000");
            int b = parseInt(spinner3.getValue().toString());
            label3.setText("El precio es: " + (a * b));
        }
    }//GEN-LAST:event_spinner3StateChanged

    private void spinner4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner4StateChanged
        // TODO add your handling code here:
        if (spinner4.getValue().toString().equals(0)) {
            label4.setVisible(false);
        } else {
            label4.setVisible(true);
            int a = parseInt("20000");
            int b = parseInt(spinner4.getValue().toString());
            label4.setText("El precio es: " + (a * b));
        }
    }//GEN-LAST:event_spinner4StateChanged

    private void spinner5StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner5StateChanged
        // TODO add your handling code here:
        if (spinner5.getValue().toString().equals(0)) {
            label5.setVisible(false);
        } else {
            label5.setVisible(true);
            int a = parseInt("25000");
            int b = parseInt(spinner5.getValue().toString());
            label5.setText("El precio es: " + (a * b));
        }
    }//GEN-LAST:event_spinner5StateChanged

    private void spinner6StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner6StateChanged
        // TODO add your handling code here:
        if (spinner6.getValue().toString().equals(0)) {
            label6.setVisible(false);
        } else {
            label6.setVisible(true);
            int a = parseInt("30000");
            int b = parseInt(spinner6.getValue().toString());
            label6.setText("El precio es: " + (a * b));
        }
    }//GEN-LAST:event_spinner6StateChanged

    private void spinner7StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner7StateChanged
        // TODO add your handling code here:
        if (spinner7.getValue().toString().equals(0)) {
            label7.setVisible(false);
        } else {
            label7.setVisible(true);
            int a = parseInt("16000");
            int b = parseInt(spinner7.getValue().toString());
            label7.setText("El precio es: " + (a * b));
        }
    }//GEN-LAST:event_spinner7StateChanged

    private void spinner8StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner8StateChanged
        // TODO add your handling code here:
        if (spinner8.getValue().toString().equals(0)) {
            label8.setVisible(false);
        } else {
            label8.setVisible(true);
            int a = parseInt("19000");
            int b = parseInt(spinner8.getValue().toString());
            label8.setText("El precio es: " + (a * b));
        }
    }//GEN-LAST:event_spinner8StateChanged

    private void spinner9StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinner9StateChanged
        // TODO add your handling code here:
        if (spinner9.getValue().toString().equals(0)) {
            label9.setVisible(false);
        } else {
            label9.setVisible(true);
            int a = parseInt("19000");
            int b = parseInt(spinner9.getValue().toString());
            label9.setText("El precio es: " + (a * b));
        }
    }//GEN-LAST:event_spinner9StateChanged

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlatosFuertes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlatosFuertes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JTable TablaPedidos;
    private javax.swing.JButton back;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label10;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JLabel label9;
    private javax.swing.JButton pedirButtom;
    private javax.swing.JButton plato1;
    private javax.swing.JButton plato2;
    private javax.swing.JButton plato3;
    private javax.swing.JButton plato4;
    private javax.swing.JButton plato5;
    private javax.swing.JButton plato6;
    private javax.swing.JButton plato7;
    private javax.swing.JButton plato8;
    private javax.swing.JButton plato9;
    public static javax.swing.JSpinner spinner1;
    public static javax.swing.JSpinner spinner2;
    public static javax.swing.JSpinner spinner3;
    public static javax.swing.JSpinner spinner4;
    public static javax.swing.JSpinner spinner5;
    public static javax.swing.JSpinner spinner6;
    public static javax.swing.JSpinner spinner7;
    public static javax.swing.JSpinner spinner8;
    public static javax.swing.JSpinner spinner9;
    // End of variables declaration//GEN-END:variables
}
